
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library('papaja')

df_results <- readRDS('final_results.rds')

# False positive results
fp_savage_dickey_bf_conv <- round((sum(df_results$fp_savage_dickey_bf_conv)/nrow(df_results))*100,2)

fp_directional_bf_conv <- round((sum(df_results$fp_directional_bf_pos_conv,
                                     df_results$fp_directional_bf_neg_conv)/nrow(df_results))*100,2)

fp_p_effect_conv <- round((sum(df_results$fp_p_effect_pos_conv,
                               df_results$fp_p_effect_neg_conv)/nrow(df_results))*100,2)

fp_hdi_conv <- round((sum(df_results$fp_hdi_pos_conv,
                          df_results$fp_hdi_neg_conv)/nrow(df_results))*100,2)

fp_overall <- round((sum(df_results$fp_savage_dickey_bf_conv,
                         df_results$fp_directional_bf_pos_conv,
                         df_results$fp_directional_bf_neg_conv,
                         df_results$fp_p_effect_pos_conv,
                         df_results$fp_p_effect_neg_conv,
                         df_results$fp_hdi_pos_conv,
                         df_results$fp_hdi_neg_conv)/(nrow(df_results)*4))*100,2)

# Diverging results (first method shows effect, second method not)
dr_savage_dickey_bf_directional_bf <- sum(df_results$fp_savage_dickey_bf_conv == 1 &
                                            df_results$fp_directional_bf_pos_conv == 0 &
                                            df_results$fp_directional_bf_neg_conv == 0)

dr_savage_dickey_bf_hdi <- sum(df_results$fp_savage_dickey_bf_conv == 1 &
                                 df_results$fp_hdi_pos_conv == 0 &
                                 df_results$fp_hdi_neg_conv == 0)

dr_savage_dickey_bf_p_effect <- sum(df_results$fp_savage_dickey_bf_conv == 1 &
                                      df_results$fp_p_effect_pos_conv == 0 &
                                      df_results$fp_p_effect_neg_conv == 0)

dr_directional_bf_savage_dickey_bf <- sum(df_results$fp_directional_bf_pos_conv == 1 &
                                            df_results$fp_savage_dickey_bf_conv == 0,
                                          df_results$fp_directional_bf_neg_conv == 1 &
                                            df_results$fp_savage_dickey_bf_conv == 0)

dr_directional_bf_hdi <- sum(df_results$fp_directional_bf_pos_conv == 1 &
                               df_results$fp_hdi_pos_conv == 0,
                             df_results$fp_directional_bf_neg_conv == 1 &
                               df_results$fp_hdi_neg_conv == 0)

dr_directional_bf_p_effect <- sum(df_results$fp_directional_bf_pos_conv == 1 &
                                    df_results$fp_p_effect_pos_conv == 0,
                                  df_results$fp_directional_bf_neg_conv == 1 &
                                    df_results$fp_p_effect_neg_conv == 0)

dr_hdi_savage_dickey_bf <- sum(df_results$fp_hdi_pos_conv == 1 &
                                 df_results$fp_savage_dickey_bf_conv == 0,
                               df_results$hdi_neg_conv == 1 &
                                 df_results$fp_savage_dickey_bf_conv == 0)

dr_hdi_directional_bf <- sum(df_results$fp_hdi_pos_conv == 1 &
                               df_results$fp_directional_bf_pos_conv == 0,
                             df_results$fp_hdi_neg_conv == 1 &
                               df_results$fp_directional_bf_neg_conv == 0)

dr_hdi_p_effect <- sum(df_results$fp_hdi_pos_conv == 1 &
                         df_results$fp_p_effect_pos_conv == 0,
                       df_results$fp_hdi_neg_conv == 1 &
                         df_results$fp_p_effect_neg_conv == 0)

dr_p_effect_savage_dickey_bf <- sum(df_results$fp_p_effect_pos_conv == 1 &
                                      df_results$fp_savage_dickey_bf_conv == 0,
                                    df_results$hdi_p_effect_neg_conv == 1 &
                                      df_results$fp_savage_dickey_bf_conv == 0)

dr_p_effect_directional_bf <- sum(df_results$fp_p_effect_pos_conv == 1 &
                                    df_results$fp_directional_bf_pos_conv == 0,
                                  df_results$fp_p_effect_neg_conv == 1 &
                                    df_results$fp_directional_bf_neg_conv == 0)

dr_p_effect_hdi <- sum(df_results$fp_p_effect_pos_conv == 1 &
                         df_results$fp_hdi_pos_conv == 0,
                       df_results$fp_p_effect_neg_conv == 1 &
                         df_results$fp_hdi_neg_conv == 0)
```

# **False positive results**
With conventional decision thresholds, `r fp_overall` % of all hypothesis tests produced a false positive result. `r fp_savage_dickey_bf_conv` % of Savage-Dickey BFs, `r fp_directional_bf_conv` % of dBFs, `r fp_p_effect_conv` % of P(effect > 0) proportions and `r fp_hdi_conv` % of HDI decisions were false positive.

# **Diverging results**
xx


